---
- name: Install some companion packages from aur
  kewlfft.aur.aur:
    use: 'makepkg'
    name: "{{ item }}"
    state: 'present'
  loop:
    - 'companion'
  become: true
  become_user: aur_builder
