---
- name: Optionally run versionscheck if enabled
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Install some packages
  ansible.builtin.include_tasks:
    file: 'packages.yml'

- name: Install some packages from aur
  ansible.builtin.include_tasks:
    file: 'aur_packages.yml'
