---
- name: Create Group autologin
  become: true
  ansible.builtin.group:
    name: 'autologin'
    state: 'present'

- name: Add voc to autologin group
  become: true
  ansible.builtin.user:
    name: 'voc'
    groups: 'autologin'
    append: true

- name: Create lightdm config
  become: true
  ansible.builtin.template:
    src: 'templates/lightdm.conf.j2'
    dest: '/etc/lightdm/lightdm.conf'
    mode: '0644'
    group: 'root'
    owner: 'root'
    backup: true
