---
- name: Optionally run versionscheck if enabled
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Install lightdm
  ansible.builtin.include_tasks:
    file: 'packages.yml'

- name: Configure autologin un lightdm
  ansible.builtin.include_tasks:
    file: 'lightdm.yml'
