---
- name: Create tmux configuration for root
  become: true
  ansible.builtin.template:
    src: 'templates/tmux.conf.j2'
    dest: '/root/.tmux.conf'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'

- name: Create tmux configuration for voc
  become: true
  ansible.builtin.template:
    src: 'templates/tmux.conf.j2'
    dest: '/home/voc/.tmux.conf'
    owner: 'voc'
    group: 'voc'
    mode: 'u=rw,g=r,o=r'

- name: Create vimrc configuration per defined user
  become: true
  ansible.builtin.template:
    src: 'templates/tmux.conf.j2'
    dest: "{{ user.home | default('/home/' + user.name) }}/.tmux.conf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0640'
  loop: "{{ users__voc_users }}"
  loop_control:
    label: "user={{ user.name }}"
    loop_var: user
  when: user.state | default ('present') == 'present'
