---
- name: Optionally run versionscheck if enabled
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Install decklink drivers
  ansible.builtin.include_tasks:
    file: 'packages.yml'

- name: Reinstall linux headers
  ansible.builtin.include_tasks:
    file: 'linux_headers.yml'
