---
- name: Start service DesktopVideoHelper.service
  become: true
  ansible.builtin.systemd_service:
    name: 'DesktopVideoHelper.service'
    state: 'started'
    enabled: true
    daemon_reload: true
