---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when:
    - ansible_facts['pkg_mgr'] == "apt"

- name: Install sudo
  become: true
  ansible.builtin.package:
    name: 'sudo'
    state: present

- name: Set root password
  become: true
  ansible.builtin.user:
    name: 'root'
    password: "{{ users__voc_root_pwd }}"
    state: present
