---
- name: Optionally run versionscheck if enabled
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Install obs-studio reuqirements
  ansible.builtin.include_tasks:
    file: 'packages.yml'

- name: Install obs-studio using aur
  ansible.builtin.include_tasks:
    file: 'aur_packages.yml'

- name: Create folders for recording
  ansible.builtin.include_tasks:
    file: 'folders.yml'
