---
- name: Optionally run versionscheck if enabled
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Download media files for obs szene
  ansible.builtin.include_tasks:
    file: obs_media_files.yml
