---
- name: Create systemd unit for syncthing
  become: true
  ansible.builtin.template:
    src: 'templates/syncthing.service.j2'
    dest: '/lib/systemd/system/syncthing.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'systemctl restart syncthing.service'

- name: Start syncthing service
  become: true
  ansible.builtin.systemd_service:
    name: 'syncthing.service'
    state: 'started'
    daemon_reload: true
    enabled: true

