---
obs__packages:
  - 'ffmpeg'
  - 'ffmpeg4.4'
  - 'gstreamer'
  - 'vlc'
  - 'mpv'
  - 'asio'
  - 'cmake'
  - 'extra-cmake-modules'
  - 'ffnvcodec-headers'
  - 'nlohmann-json'
  - 'swig'
  - 'websocketpp'
  - 'librist'
  - 'qt6-wayland'

obs_local__media_files:
  - src: 'files/placeholder_cam1.png'
    dest: 'placeholder_cam1.png'
  - src: 'files/placeholder_cam2.png'
    dest: 'placeholder_cam2.png'
  - src: 'files/placeholder_cam3.png'
    dest: 'placeholder_cam3.png'
  - src: 'files/placeholder_slides.png'
    dest: 'placeholder_slides.png'
  - src: 'files/placeholder_stage_display.png'
    dest: 'placeholder_stage_display.png'

playbook_version_number: 6
obs__playbook_version_path: 'l3d.voc.obs.version'
